### ISSUE TITLE
Timeout tests do not pass

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js-env-phantomjs#20]
They are currently ignored. This might be due to https://github.com/scala-js/scala-js/issues/3420, so we should revisit when that issue is fixed.

**Comment by gzm0** [comment]
Fixed in 04c7bb27a79cb7addf1aa99deccddc7ffc27200a by upgrading to Scala.js 1.0.0-M6 which fixed scala-js/scala-js#3420.
